### ISSUE TITLE
I18N-ISSUE-401: Clarify initial letter requirements and alignment points

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#1]
[moving here from tracker]

http://www.w3.org/TR/2014/WD-ilreq-20141216/#first-letter
5.1 First Letter

This issue attempts to summarise various questions related to the First Letter section, which needs some clarification about requirements for positioning of highlighted 'initial letters'.

It currently says "in Devanagari the hanging baseline may be preferred".

This wording implies that in other cases the hanging baseline may not be preferred. If so, and if this refers to drop intial letters, what are the alternatives, and what are the font metrics or other considerations involved in alignment?

Are sunken and raised initial letters required, in addition to the drop initial? If so, what are the alignment points to be used for those?

See also Dave Cramer's email request (http://lists.w3.org/Archives/Public/public-i18n-indic/2014OctDec/0038.html)

> I'm working on the CSS Line Layout specification [1], which covers
>  drop caps and other initial letter effects. I was very happy to see
>  examples of this in the Indic Layout Requirements document [2].
> 
>  Can you clarify the bottom alignment point of the initial letter? The
>  text mentions the text-after-edge, but the illustrations are not
>  completely clear to me. Is there something in the font metrics that
>  would define this?
> 
>  [1] http://dev.w3.org/csswg/css-inline/
>  [2] http://www.w3.org/TR/2014/WD-ilreq-20141216/#first-letter

The text "the primary connection point connects the text-after-edge of the initial letter with the text-after-edge of the nth line, but the secondary connection point connects the hanging baselines of the initial letter and the initial line" isn't very clear, and doesn't seem to clearly relate to what is shown in the pictures.

It will probably help to look through http://dev.w3.org/csswg/css-inline/#initial-letter-styling section 2, to get ideas for the topics to cover in ilreq. It would be good to note which requirements are _and_ are not relevant to indic scripts, and what differences need to be taking into account in the way initial letters are positioned. (For example, is the formula at http://dev.w3.org/csswg/css-inline/#sizing-initial-letters relevant?)

**Comment by slata** [comment]
We clarify these issues  and updation in the new branch slata/ilreq and submitted the pull request.

**Comment by lianghai** [comment]
The latest version of this section looks much more informative.

Note, it might be hard for layout engines to find reliable values (headline height, height of Indic letters' main bodies, etc) of those metrics needed in styling initial letters since font developers don't have place in font files or just don't supply them. Therefore heuristic algorithms will be needed to generate those metrics values and it'll be a good idea to provided some guidelines, say, use the glyph of "क" to find a headline height for Devanagari.
