### ISSUE TITLE
Inherent vowel sound or transcription? 

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#14]
[i did a quick review of the document. This is the first of a number of issues i'm raising as a result.]

1.2 Indian language complexities
http://w3c.github.io/ilreq/#h-h_indian_language_complexities

> They are all abugidas in which most symbols stand for a consonant plus an inherent vowel (usually the sound /a/).

The /.../ indicates a phonemic representation, which in this case i believe is actually /ə/, whereas the 'a' is a common transliteration form.  I suspect that either the a should be changed to ə, or the slashes should be replaced with quotes.

**Comment by slata** [comment]
The changes have been made.

**Comment by lianghai** [comment]
In Hindi the inherent vowel does tend to be [ə] if not stressed, but [ə] as the inherent vowel is not really more common than [ɐ, a, ɔ…] in various languages.

Actually I think ILReq should really be cautious on its scope. Such phonetics/phonology information is hardly relevant to this doc and could be misleading if not elaborated.

**Comment by Richard57** [comment]
/a/ is phone_m_ic notation, not phone_t_ic notation.  Therefore, to expand on Panini ("a a"), we may write /a/ but say [ɐ].

**Comment by r12a** [comment]
I believe this issue can be closed, after the edit at https://github.com/w3c/ilreq/commit/33e2c153b985d1aec5d08c7c59ebe7b6aa7521e7
