### ISSUE TITLE
Variable spelling for purnaviram

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#16]
3. Text segmentation
http://w3c.github.io/ilreq/#h_text_segmentation

> sentence boundaries like the double poorna virama  

vs. 

> phrase separator called Danda or purnaviram

**Comment by slata** [comment]
The changes have been made in the draft as suggested.

**Comment by lianghai** [comment]
There must be a section explaining what transliteration scheme is used. Also, common spellings and accurate transliterations should be distinguished with different text style.

**Comment by slata** [comment]
The changes of common spellings has been made.
