### ISSUE TITLE
Unicode code point values in text

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#17]
3. Text segmentation
http://w3c.github.io/ilreq/#h_text_segmentation

I suggest to also add Unicode code point values, eg. 

> phrase separator called Danda or purnaviram (U+0964 DEVANAGARI DANDA ।) and double danda (U+0965 DEVANAGARI DOUBLE DANDA ॥), which is used to mark end of the verse.

**Comment by slata** [comment]
The changes have been made in the draft as suggested.

**Comment by lianghai** [comment]
It's messy to provide inline Unicode character information instead of linking them to some centralized section, but if have to, it's clearer to having the "U+" value and character name follow the character representation:

> … "double danda" (॥, U+0965 DEVANAGARI DOUBLE DANDA) …

**Comment by r12a** [comment]
I disagree with removing code points and character names to a central location – that can make it a pain to read the document, because you constantly have to jump elsewhere and back to find out what you are reading about.  I also think it doesn't look particularly less messy if the editor uses the `<span class="uname">` markup suggested in the [style guidelines](http://w3c.github.io/i18n-activity/guidelines/editing#inline) (which haven't been used in this case).

The text currently has 

> separator called purna viram (। , U+0964 ) and deergh viram( ॥ , U+0965 ) used...

Since the names used are Hindi, I actually think that it would be helpful to include the Unicode names of these characters, ie. 

> separator called purna viram (। , U+0964 DEVANAGARI DANDA) and deergh viram (॥ , U+0965 DEVANAGARI DOUBLE DANDA) used ...

(but add the inline markup around the U+...DANDA)

To be honest, i i had written that i'd have probably written

> separator । , U+0964 DEVANAGARI DANDA, (called _purna viram_ in Hindi) and ॥ , U+0965 DEVANAGARI DOUBLE DANDA, (_deergh viram_ in Hindi) used ...

where the hindi words are inside `<i class="foreign"` markup to produce the italicisation.

**Comment by slata** [comment]
The changes has been made.
