### ISSUE TITLE
Two dandas or double danda ?

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#18]
Text segmentation
http://w3c.github.io/ilreq/#h_text_segmentation

note that the current text uses two dandas together to show the double danda, rather than the unicode code point - some explanation would be useful here if that is intentional, or if it is commonly found in text – especially around what to do wrt segmentation, given that a two-character sequence is not like the full stop it is equated with at the end of the paragraph.

**Comment by slata** [comment]
The code points of Danda and Double Danda has been reflected in the document.

**Comment by lianghai** [comment]
Yes, commonly seen nonstandard sequence such as `<danda, danda>` instead of `<double danda>`, `<space, danda>` instead of `<danda>` for sentence termination, should be documented as "commonly found in text" as be explained why they're commonly used and how should they be handled.

**Comment by slata** [comment]
The changes has been made in the commit 5e4cfb8
