### ISSUE TITLE
Hyphenation case 1 and 2 intentions

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#21]
4.1 Hyphenation
Case 1
http://w3c.github.io/ilreq/#h_hyphenation

the example

> नर- नारी, लाभ- हानि, माता-पिता, ऊंच - नीच

has different configurations of spaces around the hyphen - is this intentional?  if so, what does it mean?  if not, we should fix the example (and add a few words to introduce it).

Am i right to assume that in case 1 the hyphens always appear in the text?  If so, what happens at the end of a line?  Does the hyphen remain on the first line or move to the second, or does it disappear?

Presumably case 2 is intended to show a situation where hyphens only appear when a line is broken inside a word.  Again, presumably the hyphen remains on the first line(?) - ilreq should clarify that.

**Comment by slata** [comment]
The relevant changes have been made. The language specific morpho-phonemic rules and industry practices (from media, publishing and grammar books) could be used for hyphen in the first line. However U+ 00AD (soft hyphen) is used in some languages such as Tamil and Malayalam.

**Comment by lianghai** [comment]
@r12a: Yeah the case 1 is just like hyphenated compound words in English, and modern typography practices in India is not matured enough to commonly distinguish hyphen and en dash. The case 2 is just like how English is hyphenated when doing line breaking, while per-orthographical-syllable line breaking is already the best people hope for therefore dictionary-based line breaking is not common. Yeah these should be clarified.

@slata: Afaik, U+00AD SHY is used by some Tamil publishers merely to aid the lack of good hyphenation dictionaries and algorithm. For such usage it's just an ad-hoc and in-house solution, not a widespread special use case. Or is there some special common uses of SHY?

**Comment by r12a** [comment]
As for other images in the document, the image in this section is a little too small to be easily seen. Can we make it bigger?

The words chosen as illustrations break at the end of the line on the left in the middle of a consonant cluster, showing a virama.  Why would it do that, rather than wrap the whole word to the next line?  Why would it break inside a consonant cluster, given the rules in section 2?  The wording 

> Following example shows correct representation of word आकर्षण and विज्ञापन using hyphen: 

could actually be saying that either the left side or the boxes to the right show correct behaviour.  I think we should do one of two things:

1. make it clearer that the left part of the image is intentionally broken by describing that in the text
2. show words wrapped onto the next line with a space at the end of the line, so the right hand boxes show how that space could be reduced with hyphenation

**Comment by slata** [comment]
While using the word-wrap property in the text of the left box, the some word breaks at the end of line shows incorrect text segmentation. The word breaks at the middle consonant cluster showing the virama. The intention of the right box is to show the correct segmentation by usage of hyphen.
