### ISSUE TITLE
Change case 2 example to show intended result

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#22]
4.1 Hyphenation
Case 2
http://w3c.github.io/ilreq/#h_hyphenation

> In the below screenshot, words आकर्षण and विज्ञापन not follow Indic orthographic syllable definition in some of the browsers.

I think it's more important to show what one should see, rather than to point out a browser-specific issue.  I think the image should be replaced (by a figure) showing the expected behaviour.

**Comment by slata** [comment]
The image is replaced with new figure.

**Comment by lianghai** [comment]
The image is still there in the gh-pages branch. Or is there a newer branch I should check?

**Comment by slata** [comment]
The image is replaced with new one.
