### ISSUE TITLE
Remove heading for section 5

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#23]
5. Requirements for Indic Layout
http://w3c.github.io/ilreq/#h_requirements_for_indic_layout

i would suggest removing this heading and moving the headings currently contained in section 5 up a level.  The previous sections, and indeed the document as a whole, are also requirements for indic layout.

**Comment by slata** [comment]
The changes have been made in the document. And the new pull request has been made for the same.

**Comment by lianghai** [comment]
@slata: For such responses, please refer to the exact commit in which the change has been introduced.

**Comment by r12a** [comment]
It doesn't look to me as if the changes have been made. I was expecting to see:

1. Introduction
2. Indic orthographic syllable boundaries
3. Text segmentation
4. Line breaking
5. Initial letter styling
etc.

**Comment by slata** [comment]
@r12a : The sections has been updated as suggested by you..
