### ISSUE TITLE
Letter-spacing questions

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#24]
5.2 Letter Spacing
http://w3c.github.io/ilreq/#h_letter_spacing

what is letter-spacing used for in indic scripts?  
how common is it?
what is the typical amount of inter-syllable spacing used, and are there limits to bear in mind?
does it vary by script?

**Comment by slata** [comment]
The letter spacing is mostly common in posters/banners/ name plates and newspaper word puzzles etc. There is no specific limit of inter syllable spacing for Indic scripts. But the only thing is that letter spacing in all Indian languages must follow Indic Orthographic syllable definition.

**Comment by lianghai** [comment]
Agree with @slata's comment above. Increased inter-orthographical-syllable spacing is a common style.

**Comment by r12a** [comment]
This is useful information, but i was hoping to see it in the document.

**Comment by r12a** [comment]
Thank you for adding the information above, but the document still doesn't clearly indicate  what is the meaning or intended effect of the letter-spacing. At a guess i'd say that for posters and banners it is a means of highlighting phrases or making them more prominent rather than emphasis.  Maybe that's the same for name plates (?), but what kind of name plate do we mean here (i also assume that we're not talking about separating initials).  How common is it to find this letter-spacing convention in the named contexts, and then also in typical web pages?

**Comment by slata** [comment]
In some of the languages like Bengali letter spacing is more prevalent .  In Hindi , which is the largest speaking language in India the  character spacing is sometimes used.Also it is used for decorative style of writing such as Newspaper Column , banner etc. In some tourist famous places it is used in nameplates. The example are shown in the draft.
