### ISSUE TITLE
Introduction of ABNF in section 2.2 should be streamlined.

### ISSUE THREAD

**Issue by asmusf** [w3c/ilreq#32]
What does this sentence mean: "The motive principle for ABNF is to describe a formal system of a language to be used as a bidirectional communications protocol."?

The entire opening paragraph (above the ABNF expression) in section 2.2 does not contribute to the understanding of the Indic issues. ABNF is something that can simply be referenced as it is done in the third sentence.

In fact, the text would be improved if it read something like this (insertions shown with []):

~~Augmented Backus–Naur Form (ABNF) is a meta-language based on Backus–Naur Form (BNF), but consisting of its own syntax and derivation rules. The motive principle for ABNF is to describe a formal system of a language to be used as a bidirectional communications protocol.~~
The linguistic definition of Indic orthographic syllable has been mapped to [the following] ABNF (Augmented Backus–Naur Form)[.]

V[m] |{CH}C[v][m]|CH

[This definition of an Indic orthographic syllable may be used] for the purpose of text segmentation, line breaking , drop letter, letter spacing in horizontal text and vertical text representation. The definition has been elaborated ~~, taking Hindi as an example.~~ [using examples from various Indic scripts in the table below.]

**Comment by r12a** [comment]
This seems to be addressed in https://github.com/w3c/ilreq/commit/84d005d850e41e82ea19cb4c7e1f7ac5b76d7377

@asmusf are you satisfied with those changes?
