### ISSUE TITLE
Inline Alignment

### ISSUE THREAD

**Issue by fantasai** [w3c/ilreq#40]
Wanted to know more about how each type of Indic script aligns text content of varying font sizes on a single line, and if there are any variations in the practice.

**Comment by r12a** [comment]
@fantasai you should raise this question in the IIP repo.  A similar issue is https://github.com/w3c/iip/issues/44.

It would probably be useful to mention that you have a need for this information. (And any pointers to a CSS spec where that is relevant would probably be useful.)  That is currently a discussion to help draft the relevant section in devanagari, but i can put an 'info request' label on it (which will also make it show up in our tracker).

So i'll close the issue in this repo.
