### ISSUE TITLE
Indic Layout Requirements spec is wrong classified/tagged at W3C

### ISSUE THREAD

**Issue by lcchueri** [w3c/ilreq#42]
"Indic Layout Requirements spec is tagged as "Accessibility" instead of "i18n" in "All Standards and Drafts" page at W3C.

**Comment by r12a** [comment]
Thanks. I'll ask the webmaster to look into it.

**Comment by xfq** [comment]
Link to the page: https://www.w3.org/TR/?title=indic

**Comment by deniak** [comment]
Thanks for the report. It should now be fixed.
