### ISSUE TITLE
Reduce duplication in orthographic syllable tables

### ISSUE THREAD

**Issue by r12a** [w3c/ilreq#7]
I just read through the new material in section 2.4:

2.4 Use cases of ABNF based Indic orthographic syllable definition for other languages
http://w3c.github.io/ilreq/#use-cases-of-abnf-based-indic-orthographic-syllable-definition-for-other-languages

I don't think i missed anything, but after a while i realised that actually the only difference between this and section 2.3 on Hindi is the set of examples.

Why don't we just add an extra column to the tables in section 2.2, and give the column the title 'Examples in Kannada/Telugu' (and of course rename the Hindi column to 'Examples in Hindi')?

**Comment by lianghai** [comment]
Good to close?
